found_category = Category.create(title: 'Найденное')
lost_category = Category.create(title: 'Потерянное')
subcategory_1 = Subcategory.create(title: 'Животные')
subcategory_2 = Subcategory.create(title: 'Машины')
subcategory_2 = Subcategory.create(title: 'Документы')
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') 